### ISSUE TITLE
Not possible display content above title

### ISSUE THREAD

**Issue by avshiyanov** [regexident/DLAlertView#41]
Please add ability to display content in the top above title and message

**Comment by regexident** [comment]
This unfortunately is not gonna happen. :pensive:  For several reasons.

1. The layouting logic of `DLAlertView` in its current state is already way too complex. I thus strongly oppose making any major changes to it (other than for the sake of fixing bugs).
2. `DLAlertView` does not use AutoLayout, making it unnecessarily difficult to keep up with Apple's future framework changes (compatibility with multi-tasking in iOS 9 being one such example).
3. And last but not least the killer: `UIAlertView` has been deprecated since iOS 8 and is gone with iOS 9. 

In the words of John Cleese:

> "This parrot is no more it has ceased to be. It's expired and gone to meet its maker. 
> This is a late parrot. It's a stiff. Bereft of life, it rests in peace."

You should thus consider `DLAlertView` depredated and discontinued.
(I simply haven't yet found the time to update the README appropriately.)

One should—for one's own good—use `UIAlertController` instead.
Nobody will hinder you from forking this project and adding whatever you feel fancy for,
but I wouldn't advise going against the flow if one can help it.
